import torch
from feedforward import Feedforward
from memory import Memory
import numpy as np


class SAC:
    """Soft Actor-Critic Agent

    Parameters:
        Q function
            Q optimizer
        policy
            policy optimizer
        alpha
        tau
        gamma
        updates per step

    Interface:
        act(obs) - produce action
        train


    NOTE: Code written by hand based on knowledge from class, papers, and reading online resources.
    The agent code is not based on an existing implementation or generated by LLMs, 
    but it uses a similar structure and utility files from the DDPG homework.

    Sources:
    1. https://spinningup.openai.com/en/latest/algorithms/sac.html
    2. https://arxiv.org/pdf/1801.01290
    """


    def __init__(self, Q1, Q2, policy, alpha, gamma, buffer, fit_steps, batch_size):
        self.Q1 = Q1
        self.Q2 = Q2
        self.policy = policy
        self.alpha = alpha
        self.gamma = gamma
        self.buffer = buffer
        self.fit_steps = fit_steps
        self.batch_size = batch_size


    def act(self, obs):
        with torch.no_grad():
            actions = self.policy.sample(torch.tensor(obs[None]))
            return actions[0].detach().numpy()
    
    def state(self):
        return (self.Q1.state_dict(), self.Q2.state_dict(), self.policy.state_dict())
    
    def get_batch(self):
        to_torch = lambda x: torch.from_numpy(x.astype(np.float32))
        data=self.buffer.sample(batch=self.batch_size)
        s = to_torch(np.stack(data[:,0])) # s_t
        a = to_torch(np.stack(data[:,1])) # a_t
        rew = to_torch(np.stack(data[:,2])[:,None]) # rew  (batchsize,1)
        s_prime = to_torch(np.stack(data[:,3])) # s_t+1
        done = to_torch(np.stack(data[:,4])[:,None])
        return s, a, rew, s_prime, done

    def train(self):
        for i in range(self.fit_steps):
            state, action, reward, next_state, done = self.get_batch()
            next_action = self.policy.sample(state)
            t = self.compute_t(next_state, next_action)
            target = self.compute_target(t, reward, done)
            self.Q1.fit(state, action, target)
            self.Q2.fit(state, action, target.clone())
            self.policy.step(t)
            self.update_targets()

    def compute_t(self, s_p, a_p):
        logprob = self.policy.logprob(s_p, a_p)
        q1 = self.Q1.target_val(s_p, a_p) 
        q2 = self.Q2.target_val(s_p, a_p)
        t1 = q1 - self.alpha * logprob
        t2 = q2 - self.alpha * logprob
        return torch.min(t1, t2)
    
    def compute_target(self, t, r, d):
        y = r + self.gamma * (1-d) * t
        return y

    def update_targets(self):
        self.Q1.polyak_update()
        self.Q2.polyak_update()

    def store_transition(self, trans):
        self.buffer.add_transition(trans)
    

class QFunction(torch.nn.Module):
    def __init__(self, base, target, optim, loss, tau):
        super().__init__()
        # TODO: Setup network with right input and output size (using super().__init__)
        self.model = base
        self.target = target
        self.target.load_state_dict(base.state_dict())
        self.tau = tau

        # END
        self.optimizer=optim
        self.loss = loss

    def fit(self, observations, actions, targets): # all arguments should be torch tensors
        self.train() # put model in training mode
        self.optimizer.zero_grad()
        # Forward pass

        pred = self.Q_value(observations,actions)
        # Compute Loss
        loss = self.loss(pred, targets)

        # Backward pass
        loss.backward()
        self.optimizer.step()
        return loss.item()
    
    def target_val(self, observations, actions):
        # TODO: implement the forward pass.
        return self.target(torch.cat((observations, actions), dim=-1))

    def Q_value(self, observations, actions):
        # TODO: implement the forward pass.
        return self.model(torch.cat((observations, actions), dim=-1))
    
    def polyak_update(self):
        Q_dict = self.model.state_dict()
        target_dict = self.target.state_dict()
        new_dict = {}
        with torch.no_grad():
            for k in Q_dict:
                new_dict[k] = self.tau * target_dict[k] + (1-self.tau) * Q_dict[k]
        self.target.load_state_dict(new_dict)
    

class TanhGaussianPolicy:

    def __init__(self, base_net, optim, action_space):
        self.base_net = base_net
        self.optimizer = optim
        self.action_space = action_space
        self.act_dim = self.action_space.shape[0]
        self.act_scale = torch.Tensor((self.action_space.high - self.action_space.low) * 0.5)
        self.act_offset = torch.Tensor((self.action_space.high + self.action_space.low) * 0.5)

    def forward(self, state):
        output = self.base_net(state)
        mu = output[:, :self.act_dim]
        logsig = output[:, self.act_dim:]
        return mu, logsig

    def step(self, t):
        self.train() # put model in training mode
        self.optimizer.zero_grad()
        # Forward pass

        # Compute Loss
        loss = -torch.mean(t)

        # Backward pass
        loss.backward()
        self.optimizer.step()
        return loss.item()
    
    def scale(self, act):
        return self.act_scale * act + self.act_offset

    def sample(self, state):
        eps = torch.randn(state.shape[0], self.act_dim)
        mu, logsig = self.forward(state)
        raw_act = torch.tanh(mu + torch.exp(logsig) * eps)
        return self.scale(raw_act)

    def logprob(self, state, action):
        mu, logsig = self.forward(state)
        inv_scaled = (action - self.act_offset) / self.act_scale
        x = torch.atanh(inv_scaled)
        lognorm = -0.5 * torch.log(2*torch.tensor(torch.pi)) - logsig - 0.5 * torch.exp(-2 * logsig) * (x - mu) ** 2
        logprob = lognorm - torch.log(self.act_scale) - torch.log(1 - inv_scaled ** 2)
        return logprob